Refactored to use actual IPs and importantly to pull different sites from each IP and place them in correct folders.

diff --git a/collectBackups b/collectBackups
--- a/collectBackups
+++ b/collectBackups
@@ -13,28 +13,46 @@
 #   Retrieval must use a asymmetric key pair
 
 ## Variables
+identityFilePath="/home/webadmin/.ssh/id_rsa"
+identityUsername="backupadmin"
 currentDate="$(date +%Y%m%0d)"
 
-currentYear=$(date +%Y)
-maxYears=6
-oldestYear=$(expr $currentYear - $maxYears)
-
+currentYear="$(date +%Y)"
 #currentMonth="$(date +%m)"
 currentMonth=01
-maxMonths=12 # This doesn't actually do anything. The number of months to use 
-             #is set in the for loop within monthly_rotation ()
-
 #currentDay="$(date +%0d)"
 currentDay=01
 
-dest_dir="/home/webadmin/backups/"
-old_dir="/home/webadmin/backups/removedBackups/"
+maxYears=6
+
+oldestYear=$(expr $currentYear - $maxYears)
+
+maxMonths=12 # This doesn't actually do anything. The number of months to use 
+             #is set in the for loop within monthly_rotation ()
+
+destDir="/home/webadmin/backups/"
+oldDir="/home/webadmin/backups/removedBackups/"
 fileExtension=".tar.gz2"
 
-#src_serverNames=(amm lm mam)
-src_serverNames=(amm)
 
-echo "The source server names are: ${src_serverNames[@]}"
+#serverNameToIP=( [web01]="172.16.208.19" [dev01]="172.16.208.18" [doweb01]="138.68.22.172" );
+# Declaring this is important because later indexing from the array doesn't get the right value otherwise
+declare -A serverNameToIP
+serverNameToIP=([web01]="97.93.161.251" [dev01]="97.93.161.250" [doweb01]="138.68.22.173");
+
+web01Sites=( "testingamm" )
+doweb01Sites=(  "amm" "mam" )
+dev01Sites=( "amm" )
+
+# The srcServerNames array may need to be created dynamically maybe by pulling file lists
+# from each server and searching for the first part of each file name 
+
+
+
+#srcServerNames=( "web01" "dev01" "doweb01" )
+srcServerNames=( "dev01" )
+
+echo "The source server names are: ${srcServerNames[@]}"
 
 is_directory () {
     # Return when the argument is longer than 0 and a valid directory
@@ -107,25 +125,25 @@ daily_rotation () {
     
     keyword=daily
 
-    file_count=$(count_files $path $keyword);
+    fileCount=$(count_files $path $keyword);
     
-    echo "Starting number of $keyword files: $file_count";
+    echo "Starting number of $keyword files: $fileCount";
 
-    if [[ ${file_count} -ge 7 ]]; then
+    if [[ ${fileCount} -ge 7 ]]; then
         echo "";
         echo "Files older than 7 days from $currentDate";
         find ${path} -mtime +7 -iname "*daily*";
         
         echo "";
-        echo "Old files will be ''deleted'' to ${old_dir}";
-        find ${path} -mtime +7 -iname "*daily*" -exec mv '{}' ${old_dir} \; ;
+        echo "Old files will be ''deleted'' to ${oldDir}";
+        find ${path} -mtime +7 -iname "*daily*" -exec mv '{}' ${oldDir} \; ;
         
     fi;
     
     
-    file_count=$(count_files $path $keyword);
+    fileCount=$(count_files $path $keyword);
     echo -e "\n********************************************************************************";
-    echo -e "Ending number of $keyword files: $file_count\n";
+    echo -e "Ending number of $keyword files: $fileCount\n";
     echo "";
     ls $path | grep $keyword
 
@@ -142,9 +160,9 @@ monthly_rotation() {
 
     keyword=monthly
 
-    file_count=$(count_files $path $keyword);
+    fileCount=$(count_files $path $keyword);
     
-    echo "Total number of $keyword files: $file_count";
+    echo "Total number of $keyword files: $fileCount";
     echo ""
     ls ${path} | grep $keyword 
 
@@ -212,9 +230,9 @@ yearly_rotation() {
 
     keyword=yearly
    
-    file_count=$(count_files $path $keyword);
+    fileCount=$(count_files $path $keyword);
     
-    echo "Starting number of $keyword files: $file_count";
+    echo "Starting number of $keyword files: $fileCount";
     echo ""
     ls ${path} | grep yearly
 
@@ -279,40 +297,61 @@ pull_files () {
     # Copy and rename files 
     # 
     # Arguments: $1 -> path
-    #            #2 -> server name
+    #            $2 -> server name
+    #            $3  -> site name
 
     path="${1}"; 
     serverName=${2};
-    echo -e "Target Server: $serverName\nFile destination: $path\n";
-
-    keywordArray=();
-    if [[ $(date +%m%0d) == 0101 ]]; then
-        keywordArray+=("yearly");
-    fi;
+    siteName=${3};
+   
+    serverIP=${serverNameToIP[${serverName}]};
     
-    if [[ $(date +%0d) == 01 ]]; then
-        keywordArray+=("monthly");
-    fi;
+    echo -e "Target Server: $serverName\nTarget IP: ${serverIP}\nTarget Site: $siteName\nFile destination: $path\n";
 
-    keywordArray+=("daily");
+    destFilePathName="${path}${serverName}_${siteName}_${currentDate}${fileExtension}"
+   
+    srcFileNamePath="backups/${siteName}_backup${fileExtension}";
+    echo "scp -i ${identityFilePath} ${identityUsername}@${serverIP}:${srcFileNamePath} ${destFilePathName}";
+    scp -i ${identityFilePath} ${identityUsername}@${serverIP}:${srcFileNamePath} ${destFilePathName};
     
-    echo -e "The retrieval array:\n${keywordArray[@]}\n";
-    echo ${keywordArray[1]};
-    for keyword in ${keywordArray[@]}; do
+    if ! [[ -e ${destFilePathName} ]]; then
+        echo "Something has gone wrong. After scp, ${destFilePathName} is missing.";
+        exit 1;
+    else
+        keywordArray=(daily);
+        
+        if [[ "${currentMonth}${currentDay}" == 0101 ]]; then
+            keywordArray+=("yearly");
+        fi;
+        
+        if [[ "${currentDay}" == 01 ]]; then
+            keywordArray+=("monthly");
+        fi;
 
-        fileName="${path}${serverName}_${keyword}_${currentDate}${fileExtension}"
-        echo $fileName
-    done;
-    }
+        
+        echo -e "The retrieval array:\n${keywordArray[@]}\n";
+        echo ${keywordArray[1]};
+        for keyword in ${keywordArray[@]}; do
+            
+            newFilePathName="${path}${serverName}_${siteName}_${keyword}_${currentDate}${fileExtension}"
+            cp ${destFilePathName} ${newFilePathName} 
+        done;
 
+        fileCount=$(ls ${path} | wc -l);
+        
+        if [[ ${fileCount} -ge 2 ]]; then
+            #rm ${destFilePathName};
+            ssh -i ${identityFilePath} ${identityUsername}@${serverIP} "cp ${srcFileNamePath} ${srcFileNamePath}_old && rm ${srcFileNamePath}";
+        fi
+    fi
 
+}
 
-main () {
-    for i in ${src_serverNames[@]}; do
-        server_name="${i}"
-
-        path="${dest_dir}${server_name}/";
-
+execute_things () {
+        serverName="${1}";
+        siteName="${2}";
+        path="${destDir}${serverName}/${siteName}/";
+        
         if [[ ! -d ${path} ]]; then
             mkdir -p ${path};
         fi;
@@ -321,7 +360,7 @@ main () {
         echo "Pulling backup files";
         echo -e "********************\n";
 
-        pull_files $path $server_name;
+        pull_files $path $serverName $siteName;
 
         echo "********************************"
         echo "Starting rotation of daily files"
@@ -348,7 +387,44 @@ main () {
             fi;
         fi;
 
-    done;
 }
+
+main () {
+    # For server name, find the sites then execute the pull and rotation on each site
+    for i in ${srcServerNames[@]}; do
+        serverName="${i}";
+
+        case ${serverName} in
+            doweb01)
+                for siteName in ${doweb01Sites[@]}; do
+                    echo "$serverName $siteName";
+                    exit 1;
+                    execute_things $serverName $siteName;
+                done;
+                ;;
+
+            web01)
+                for siteName in ${web01Sites[@]}; do
+                    echo "$serverName $siteName";
+                    exit 2;
+                    execute_things $serverName $siteName;
+                done;
+                ;;
+
+            dev01)
+                for siteName in ${dev01Sites[@]}; do
+                    echo "$serverName $siteName";
+                    execute_things $serverName $siteName;
+                done;
+                ;;
+            *)
+                echo "Something is missing from the main::case";
+                exit 1;
+                ;;
+
+        esac
+    done
+}
+
 
 main;
